import Head from 'next/head'
import { Roboto } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import Link from 'next/link'
import Form from '@/components/Form/Form'
import { useContext, useState } from 'react'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
})

export default function Home() {
  const handleFormSubmit = (data: any) => {
    console.log(data)
  }
  return (
    <>
      <Head>
        <title>HRNet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1 className={`${roboto.className} ${styles.description__title}`}>
            {' '}
            HRnet{' '}
          </h1>
        </div>
        <div className={styles.container}>
          <h2 className={`${roboto.className} ${styles.container__title}`}>
            Create Employee
          </h2>
          <Link
            href="employees"
            className={`${roboto.className} ${styles.btn}`}
          >
            View current employees
          </Link>
        </div>
        <Form  />
      </main>
    </>
  )
}
