import Head from 'next/head'
import { Open_Sans } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import Link from 'next/link'
import Form from '@/components/Form/Form'

const openSans = Open_Sans({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
      <Head>
        <title>HRNet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1 className={`${openSans.className} ${styles.description__title}`}> HRnet </h1>
          <Link href="employees" className={styles.description__link}>View current employees</Link>
        </div>
        <Form />
      </main>
    </>
  )
}
